version: '2'
services:
  central-registry:
    env_file: .env
    ports:
     - "3001:3001"
    depends_on:
     - mysql
    networks:
     - back
  mysql:
    env_file: .env
    image: mysql/mysql-server:5.7
    networks:
     - back
    volumes:
     - mysql-data:/var/lib/mysql
networks:
  back: {}
volumes:
  mysql-data: {}
